version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile-new
    container_name: flask_app
    ports:
      - "3000:5000"
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_DEFAULT_REGION: "ap-south-1"


