# templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  aws_access_key_id: {{ .Values.secrets.awsAccessKeyId | default "" | b64enc | quote }}
  aws_secret_access_key: {{ .Values.secrets.awsSecretAccessKey | default "" | b64enc | quote }}
