apiVersion: v1
kind: Service
metadata:
  name: {{ include "veeren-leyline.fullname" . }}
  labels:
    {{- include "veeren-leyline.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.applicationport }}
      protocol: TCP
      name: http
  selector:
    {{- include "veeren-leyline.selectorLabels" . | nindent 4 }}
